// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store.proto

package store

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Endian int32

const (
	Endian_LITTLE Endian = 0
	Endian_BIG    Endian = 1
)

var Endian_name = map[int32]string{
	0: "LITTLE",
	1: "BIG",
}

var Endian_value = map[string]int32{
	"LITTLE": 0,
	"BIG":    1,
}

func (x Endian) String() string {
	return proto.EnumName(Endian_name, int32(x))
}

func (Endian) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{0}
}

type Blob struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir                bool     `protobuf:"varint,2,opt,name=isDir,proto3" json:"isDir,omitempty"`
	Exists               bool     `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blob) Reset()         { *m = Blob{} }
func (m *Blob) String() string { return proto.CompactTextString(m) }
func (*Blob) ProtoMessage()    {}
func (*Blob) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{0}
}

func (m *Blob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blob.Unmarshal(m, b)
}
func (m *Blob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blob.Marshal(b, m, deterministic)
}
func (m *Blob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blob.Merge(m, src)
}
func (m *Blob) XXX_Size() int {
	return xxx_messageInfo_Blob.Size(m)
}
func (m *Blob) XXX_DiscardUnknown() {
	xxx_messageInfo_Blob.DiscardUnknown(m)
}

var xxx_messageInfo_Blob proto.InternalMessageInfo

func (m *Blob) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Blob) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *Blob) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

type Blobs struct {
	Blob                 []*Blob  `protobuf:"bytes,1,rep,name=blob,proto3" json:"blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blobs) Reset()         { *m = Blobs{} }
func (m *Blobs) String() string { return proto.CompactTextString(m) }
func (*Blobs) ProtoMessage()    {}
func (*Blobs) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{1}
}

func (m *Blobs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blobs.Unmarshal(m, b)
}
func (m *Blobs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blobs.Marshal(b, m, deterministic)
}
func (m *Blobs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blobs.Merge(m, src)
}
func (m *Blobs) XXX_Size() int {
	return xxx_messageInfo_Blobs.Size(m)
}
func (m *Blobs) XXX_DiscardUnknown() {
	xxx_messageInfo_Blobs.DiscardUnknown(m)
}

var xxx_messageInfo_Blobs proto.InternalMessageInfo

func (m *Blobs) GetBlob() []*Blob {
	if m != nil {
		return m.Blob
	}
	return nil
}

type ListRequest struct {
	Path                 string    `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Opts                 *ListOpts `protobuf:"bytes,2,opt,name=opts,proto3" json:"opts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{2}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ListRequest) GetOpts() *ListOpts {
	if m != nil {
		return m.Opts
	}
	return nil
}

type ListOpts struct {
	Rescursive           bool     `protobuf:"varint,1,opt,name=rescursive,proto3" json:"rescursive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOpts) Reset()         { *m = ListOpts{} }
func (m *ListOpts) String() string { return proto.CompactTextString(m) }
func (*ListOpts) ProtoMessage()    {}
func (*ListOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{3}
}

func (m *ListOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOpts.Unmarshal(m, b)
}
func (m *ListOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOpts.Marshal(b, m, deterministic)
}
func (m *ListOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOpts.Merge(m, src)
}
func (m *ListOpts) XXX_Size() int {
	return xxx_messageInfo_ListOpts.Size(m)
}
func (m *ListOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOpts.DiscardUnknown(m)
}

var xxx_messageInfo_ListOpts proto.InternalMessageInfo

func (m *ListOpts) GetRescursive() bool {
	if m != nil {
		return m.Rescursive
	}
	return false
}

type ListResponse struct {
	Blobs                *Blobs   `protobuf:"bytes,1,opt,name=blobs,proto3" json:"blobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{4}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetBlobs() *Blobs {
	if m != nil {
		return m.Blobs
	}
	return nil
}

type Stat struct {
	LastModified         int64    `protobuf:"varint,1,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	ETag                 string   `protobuf:"bytes,2,opt,name=eTag,proto3" json:"eTag,omitempty"`
	ContentType          string   `protobuf:"bytes,3,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stat) Reset()         { *m = Stat{} }
func (m *Stat) String() string { return proto.CompactTextString(m) }
func (*Stat) ProtoMessage()    {}
func (*Stat) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{5}
}

func (m *Stat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stat.Unmarshal(m, b)
}
func (m *Stat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stat.Marshal(b, m, deterministic)
}
func (m *Stat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stat.Merge(m, src)
}
func (m *Stat) XXX_Size() int {
	return xxx_messageInfo_Stat.Size(m)
}
func (m *Stat) XXX_DiscardUnknown() {
	xxx_messageInfo_Stat.DiscardUnknown(m)
}

var xxx_messageInfo_Stat proto.InternalMessageInfo

func (m *Stat) GetLastModified() int64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

func (m *Stat) GetETag() string {
	if m != nil {
		return m.ETag
	}
	return ""
}

func (m *Stat) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Stat) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type StatRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatRequest) Reset()         { *m = StatRequest{} }
func (m *StatRequest) String() string { return proto.CompactTextString(m) }
func (*StatRequest) ProtoMessage()    {}
func (*StatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{6}
}

func (m *StatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatRequest.Unmarshal(m, b)
}
func (m *StatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatRequest.Marshal(b, m, deterministic)
}
func (m *StatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatRequest.Merge(m, src)
}
func (m *StatRequest) XXX_Size() int {
	return xxx_messageInfo_StatRequest.Size(m)
}
func (m *StatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatRequest proto.InternalMessageInfo

func (m *StatRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StatResponse struct {
	Stat                 *Stat    `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatResponse) Reset()         { *m = StatResponse{} }
func (m *StatResponse) String() string { return proto.CompactTextString(m) }
func (*StatResponse) ProtoMessage()    {}
func (*StatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{7}
}

func (m *StatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatResponse.Unmarshal(m, b)
}
func (m *StatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatResponse.Marshal(b, m, deterministic)
}
func (m *StatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatResponse.Merge(m, src)
}
func (m *StatResponse) XXX_Size() int {
	return xxx_messageInfo_StatResponse.Size(m)
}
func (m *StatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatResponse proto.InternalMessageInfo

func (m *StatResponse) GetStat() *Stat {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (m *StatResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Trace                string   `protobuf:"bytes,2,opt,name=trace,proto3" json:"trace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{8}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetTrace() string {
	if m != nil {
		return m.Trace
	}
	return ""
}

type Response struct {
	Err                  *Error   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{9}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type PutPartRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Len                  int64    `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	Start                int64    `protobuf:"varint,5,opt,name=start,proto3" json:"start,omitempty"`
	Endian               Endian   `protobuf:"varint,4,opt,name=endian,proto3,enum=Endian" json:"endian,omitempty"`
	Part                 []byte   `protobuf:"bytes,3,opt,name=part,proto3" json:"part,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutPartRequest) Reset()         { *m = PutPartRequest{} }
func (m *PutPartRequest) String() string { return proto.CompactTextString(m) }
func (*PutPartRequest) ProtoMessage()    {}
func (*PutPartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{10}
}

func (m *PutPartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutPartRequest.Unmarshal(m, b)
}
func (m *PutPartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutPartRequest.Marshal(b, m, deterministic)
}
func (m *PutPartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutPartRequest.Merge(m, src)
}
func (m *PutPartRequest) XXX_Size() int {
	return xxx_messageInfo_PutPartRequest.Size(m)
}
func (m *PutPartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutPartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutPartRequest proto.InternalMessageInfo

func (m *PutPartRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PutPartRequest) GetLen() int64 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *PutPartRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *PutPartRequest) GetEndian() Endian {
	if m != nil {
		return m.Endian
	}
	return Endian_LITTLE
}

func (m *PutPartRequest) GetPart() []byte {
	if m != nil {
		return m.Part
	}
	return nil
}

type PutPartResponse struct {
	Succes               bool     `protobuf:"varint,1,opt,name=succes,proto3" json:"succes,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Len                  int64    `protobuf:"varint,3,opt,name=len,proto3" json:"len,omitempty"`
	Err                  *Error   `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutPartResponse) Reset()         { *m = PutPartResponse{} }
func (m *PutPartResponse) String() string { return proto.CompactTextString(m) }
func (*PutPartResponse) ProtoMessage()    {}
func (*PutPartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{11}
}

func (m *PutPartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutPartResponse.Unmarshal(m, b)
}
func (m *PutPartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutPartResponse.Marshal(b, m, deterministic)
}
func (m *PutPartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutPartResponse.Merge(m, src)
}
func (m *PutPartResponse) XXX_Size() int {
	return xxx_messageInfo_PutPartResponse.Size(m)
}
func (m *PutPartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutPartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutPartResponse proto.InternalMessageInfo

func (m *PutPartResponse) GetSucces() bool {
	if m != nil {
		return m.Succes
	}
	return false
}

func (m *PutPartResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PutPartResponse) GetLen() int64 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *PutPartResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type GetPartRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Len                  int64    `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	Start                int64    `protobuf:"varint,5,opt,name=start,proto3" json:"start,omitempty"`
	Endian               Endian   `protobuf:"varint,4,opt,name=endian,proto3,enum=Endian" json:"endian,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPartRequest) Reset()         { *m = GetPartRequest{} }
func (m *GetPartRequest) String() string { return proto.CompactTextString(m) }
func (*GetPartRequest) ProtoMessage()    {}
func (*GetPartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{12}
}

func (m *GetPartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPartRequest.Unmarshal(m, b)
}
func (m *GetPartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPartRequest.Marshal(b, m, deterministic)
}
func (m *GetPartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPartRequest.Merge(m, src)
}
func (m *GetPartRequest) XXX_Size() int {
	return xxx_messageInfo_GetPartRequest.Size(m)
}
func (m *GetPartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPartRequest proto.InternalMessageInfo

func (m *GetPartRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetPartRequest) GetLen() int64 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *GetPartRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GetPartRequest) GetEndian() Endian {
	if m != nil {
		return m.Endian
	}
	return Endian_LITTLE
}

type GetPartResponse struct {
	Part                 []byte   `protobuf:"bytes,1,opt,name=part,proto3" json:"part,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Len                  int64    `protobuf:"varint,3,opt,name=len,proto3" json:"len,omitempty"`
	Start                int64    `protobuf:"varint,4,opt,name=start,proto3" json:"start,omitempty"`
	Endian               Endian   `protobuf:"varint,5,opt,name=endian,proto3,enum=Endian" json:"endian,omitempty"`
	Err                  *Error   `protobuf:"bytes,6,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPartResponse) Reset()         { *m = GetPartResponse{} }
func (m *GetPartResponse) String() string { return proto.CompactTextString(m) }
func (*GetPartResponse) ProtoMessage()    {}
func (*GetPartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{13}
}

func (m *GetPartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPartResponse.Unmarshal(m, b)
}
func (m *GetPartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPartResponse.Marshal(b, m, deterministic)
}
func (m *GetPartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPartResponse.Merge(m, src)
}
func (m *GetPartResponse) XXX_Size() int {
	return xxx_messageInfo_GetPartResponse.Size(m)
}
func (m *GetPartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPartResponse proto.InternalMessageInfo

func (m *GetPartResponse) GetPart() []byte {
	if m != nil {
		return m.Part
	}
	return nil
}

func (m *GetPartResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetPartResponse) GetLen() int64 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *GetPartResponse) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GetPartResponse) GetEndian() Endian {
	if m != nil {
		return m.Endian
	}
	return Endian_LITTLE
}

func (m *GetPartResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type DeleteRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{14}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{15}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type MoveRequest struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveRequest) Reset()         { *m = MoveRequest{} }
func (m *MoveRequest) String() string { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()    {}
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{16}
}

func (m *MoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRequest.Unmarshal(m, b)
}
func (m *MoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRequest.Marshal(b, m, deterministic)
}
func (m *MoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRequest.Merge(m, src)
}
func (m *MoveRequest) XXX_Size() int {
	return xxx_messageInfo_MoveRequest.Size(m)
}
func (m *MoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRequest proto.InternalMessageInfo

func (m *MoveRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *MoveRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

type MoveResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveResponse) Reset()         { *m = MoveResponse{} }
func (m *MoveResponse) String() string { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()    {}
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{17}
}

func (m *MoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResponse.Unmarshal(m, b)
}
func (m *MoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResponse.Marshal(b, m, deterministic)
}
func (m *MoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResponse.Merge(m, src)
}
func (m *MoveResponse) XXX_Size() int {
	return xxx_messageInfo_MoveResponse.Size(m)
}
func (m *MoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResponse proto.InternalMessageInfo

func (m *MoveResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *MoveResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func init() {
	proto.RegisterEnum("Endian", Endian_name, Endian_value)
	proto.RegisterType((*Blob)(nil), "Blob")
	proto.RegisterType((*Blobs)(nil), "Blobs")
	proto.RegisterType((*ListRequest)(nil), "ListRequest")
	proto.RegisterType((*ListOpts)(nil), "ListOpts")
	proto.RegisterType((*ListResponse)(nil), "ListResponse")
	proto.RegisterType((*Stat)(nil), "Stat")
	proto.RegisterType((*StatRequest)(nil), "StatRequest")
	proto.RegisterType((*StatResponse)(nil), "StatResponse")
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*PutPartRequest)(nil), "PutPartRequest")
	proto.RegisterType((*PutPartResponse)(nil), "PutPartResponse")
	proto.RegisterType((*GetPartRequest)(nil), "GetPartRequest")
	proto.RegisterType((*GetPartResponse)(nil), "GetPartResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*MoveRequest)(nil), "MoveRequest")
	proto.RegisterType((*MoveResponse)(nil), "MoveResponse")
}

func init() { proto.RegisterFile("store.proto", fileDescriptor_98bbca36ef968dfc) }

var fileDescriptor_98bbca36ef968dfc = []byte{
	// 669 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x4d, 0x4f, 0x1b, 0x31,
	0x10, 0x65, 0xb3, 0x1f, 0x49, 0x66, 0x97, 0x10, 0x59, 0x15, 0x5a, 0xa2, 0x42, 0x83, 0xdb, 0x4a,
	0x08, 0x55, 0x96, 0x9a, 0x1e, 0x7a, 0xad, 0x28, 0x88, 0x22, 0x81, 0x8a, 0x4c, 0xfe, 0xc0, 0x26,
	0x18, 0xba, 0x52, 0xb2, 0x4e, 0xed, 0x09, 0x6a, 0x7b, 0xeb, 0xff, 0xe8, 0xef, 0xec, 0xb9, 0xb2,
	0xd7, 0xbb, 0x6c, 0x08, 0x42, 0x55, 0x0f, 0xbd, 0xcd, 0xbc, 0xcc, 0xfa, 0xbd, 0x79, 0x33, 0x76,
	0x20, 0xd6, 0x28, 0x95, 0x60, 0x0b, 0x25, 0x51, 0xd2, 0x4f, 0x10, 0x1c, 0xcd, 0xe4, 0x84, 0x10,
	0x08, 0x8a, 0x6c, 0x2e, 0x52, 0x6f, 0xe8, 0x1d, 0x74, 0xb9, 0x8d, 0xc9, 0x33, 0x08, 0x73, 0x7d,
	0x9c, 0xab, 0xb4, 0x35, 0xf4, 0x0e, 0x3a, 0xbc, 0x4c, 0xc8, 0x36, 0x44, 0xe2, 0x5b, 0xae, 0x51,
	0xa7, 0xbe, 0x85, 0x5d, 0x46, 0x29, 0x84, 0xe6, 0x24, 0x4d, 0x76, 0x20, 0x98, 0xcc, 0xe4, 0x24,
	0xf5, 0x86, 0xfe, 0x41, 0x3c, 0x0a, 0x99, 0x41, 0xb9, 0x85, 0xe8, 0x07, 0x88, 0xcf, 0x73, 0x8d,
	0x5c, 0x7c, 0x5d, 0x0a, 0x8d, 0x86, 0x74, 0x91, 0xe1, 0x97, 0x8a, 0xd4, 0xc4, 0x64, 0x17, 0x02,
	0xb9, 0x40, 0x6d, 0x39, 0xe3, 0x51, 0x97, 0x99, 0xfa, 0xcf, 0x0b, 0xd4, 0xdc, 0xc2, 0xf4, 0x10,
	0x3a, 0x15, 0x42, 0xf6, 0x00, 0x94, 0xd0, 0xd3, 0xa5, 0xd2, 0xf9, 0x5d, 0xa9, 0xbc, 0xc3, 0x1b,
	0x08, 0x7d, 0x03, 0x49, 0xc9, 0xa6, 0x17, 0xb2, 0xd0, 0x82, 0x3c, 0x87, 0xd0, 0xa8, 0xd0, 0xb6,
	0x34, 0x1e, 0x45, 0x56, 0x99, 0xe6, 0x25, 0x48, 0x11, 0x82, 0x2b, 0xcc, 0x90, 0x50, 0x48, 0x66,
	0x99, 0xc6, 0x0b, 0x79, 0x9d, 0xdf, 0xe4, 0xe2, 0xda, 0x16, 0xfb, 0x7c, 0x05, 0x33, 0xc2, 0xc5,
	0x38, 0xbb, 0xb5, 0x22, 0xbb, 0xdc, 0xc6, 0x64, 0x08, 0xf1, 0x54, 0x16, 0x28, 0x0a, 0x1c, 0x7f,
	0x5f, 0x08, 0x6b, 0x4e, 0x97, 0x37, 0x21, 0xf3, 0x95, 0xce, 0x7f, 0x88, 0x34, 0xb0, 0x27, 0xda,
	0x98, 0xee, 0x43, 0x6c, 0x58, 0x1b, 0x8e, 0x3c, 0x1c, 0x03, 0xfd, 0x08, 0x49, 0x59, 0xe2, 0xda,
	0xd8, 0x81, 0x40, 0x63, 0x86, 0xae, 0x8b, 0x90, 0xd9, 0x1f, 0x2d, 0x44, 0x52, 0xf0, 0x85, 0x52,
	0xce, 0xbb, 0x88, 0x9d, 0x28, 0x25, 0x15, 0x37, 0x10, 0x7d, 0x0f, 0xa1, 0xcd, 0x48, 0x0a, 0xed,
	0xb9, 0xd0, 0x3a, 0xbb, 0xad, 0x48, 0xaa, 0xd4, 0x8c, 0x1b, 0x55, 0x36, 0x15, 0xae, 0xab, 0x32,
	0xa1, 0xaf, 0xa0, 0x53, 0x33, 0xbb, 0xe3, 0xbd, 0xf5, 0xe3, 0x7f, 0x7a, 0xd0, 0xbb, 0x5c, 0xe2,
	0x65, 0xa6, 0x9e, 0x6a, 0x85, 0xf4, 0xc1, 0x9f, 0x89, 0xc2, 0x12, 0xf8, 0xdc, 0x84, 0x86, 0x54,
	0x63, 0xa6, 0x30, 0x0d, 0x2d, 0x56, 0x26, 0xe4, 0x05, 0x44, 0xa2, 0xb8, 0xce, 0xb3, 0xc2, 0x7a,
	0xd5, 0x1b, 0xb5, 0xd9, 0x89, 0x4d, 0xb9, 0x83, 0xcb, 0xcd, 0x51, 0x68, 0x5d, 0x4e, 0xb8, 0x8d,
	0x69, 0x0e, 0x5b, 0xb5, 0x04, 0x27, 0x78, 0x1b, 0x22, 0xbd, 0x9c, 0x4e, 0x85, 0x76, 0xdb, 0xe1,
	0xb2, 0x5a, 0x5b, 0x6b, 0x5d, 0x9b, 0x7f, 0xaf, 0xcd, 0xb5, 0x1b, 0xac, 0xb7, 0x3b, 0x87, 0xde,
	0xa9, 0xf8, 0x6f, 0xdd, 0xd2, 0x5f, 0x1e, 0x6c, 0xd5, 0x7c, 0xae, 0xb5, 0xca, 0x01, 0xef, 0xde,
	0x81, 0xbf, 0x6c, 0xab, 0x16, 0x11, 0x3c, 0x2e, 0x22, 0x7c, 0xdc, 0x72, 0xe7, 0x46, 0xb4, 0xee,
	0xc6, 0x4b, 0xd8, 0x3c, 0x16, 0x33, 0x81, 0xe2, 0xa9, 0x2d, 0x3e, 0x86, 0x5e, 0x55, 0x54, 0x6f,
	0x53, 0xbb, 0x1c, 0x47, 0x35, 0x9d, 0x2a, 0x7d, 0x62, 0x8d, 0xdf, 0x42, 0x7c, 0x21, 0xef, 0x6a,
	0xa2, 0x1e, 0xb4, 0x50, 0x3a, 0x9a, 0x16, 0x4a, 0x43, 0x7c, 0xa3, 0xe4, 0xbc, 0x32, 0xc0, 0xc4,
	0xf4, 0x08, 0x92, 0xf2, 0x93, 0x7f, 0xa7, 0x3d, 0xdc, 0x85, 0xa8, 0x74, 0x83, 0x00, 0x44, 0xe7,
	0x67, 0xe3, 0xf1, 0xf9, 0x49, 0x7f, 0x83, 0xb4, 0xc1, 0x3f, 0x3a, 0x3b, 0xed, 0x7b, 0xa3, 0xdf,
	0x1e, 0xc4, 0x5c, 0xcc, 0x25, 0x8a, 0x2b, 0xf3, 0xb4, 0x92, 0x3d, 0x08, 0xcc, 0xc3, 0x43, 0x12,
	0xd6, 0x78, 0xed, 0x06, 0xee, 0xbd, 0xa1, 0x1b, 0xe4, 0xb5, 0x7b, 0x6a, 0x12, 0xd6, 0xb8, 0xfb,
	0x83, 0x4d, 0xd6, 0xbc, 0xe6, 0x74, 0x83, 0x1c, 0x82, 0x7f, 0xb9, 0x44, 0xb2, 0xc5, 0x56, 0x6f,
	0xd6, 0xa0, 0xcf, 0x1e, 0xec, 0x79, 0x59, 0x7b, 0x2a, 0x4c, 0xed, 0xea, 0x5e, 0x0e, 0xfa, 0xec,
	0xc1, 0xe2, 0x58, 0xfa, 0xa8, 0x1c, 0x05, 0xe9, 0xb1, 0x95, 0xc1, 0x0d, 0xba, 0xac, 0x51, 0xb6,
	0x0f, 0x81, 0x31, 0x8e, 0x24, 0xac, 0x61, 0xf9, 0x4a, 0xc9, 0x24, 0xb2, 0x7f, 0x22, 0xef, 0xfe,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xe1, 0xb8, 0xcc, 0x53, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RemoteStoreClient is the client API for RemoteStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteStoreClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*Blobs, error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	Put(ctx context.Context, in *PutPartRequest, opts ...grpc.CallOption) (*PutPartResponse, error)
	Get(ctx context.Context, in *GetPartRequest, opts ...grpc.CallOption) (*GetPartResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Response, error)
	Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*Response, error)
}

type remoteStoreClient struct {
	cc *grpc.ClientConn
}

func NewRemoteStoreClient(cc *grpc.ClientConn) RemoteStoreClient {
	return &remoteStoreClient{cc}
}

func (c *remoteStoreClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*Blobs, error) {
	out := new(Blobs)
	err := c.cc.Invoke(ctx, "/RemoteStore/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteStoreClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, "/RemoteStore/Stat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteStoreClient) Put(ctx context.Context, in *PutPartRequest, opts ...grpc.CallOption) (*PutPartResponse, error) {
	out := new(PutPartResponse)
	err := c.cc.Invoke(ctx, "/RemoteStore/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteStoreClient) Get(ctx context.Context, in *GetPartRequest, opts ...grpc.CallOption) (*GetPartResponse, error) {
	out := new(GetPartResponse)
	err := c.cc.Invoke(ctx, "/RemoteStore/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteStoreClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/RemoteStore/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteStoreClient) Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/RemoteStore/Move", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteStoreServer is the server API for RemoteStore service.
type RemoteStoreServer interface {
	List(context.Context, *ListRequest) (*Blobs, error)
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	Put(context.Context, *PutPartRequest) (*PutPartResponse, error)
	Get(context.Context, *GetPartRequest) (*GetPartResponse, error)
	Delete(context.Context, *DeleteRequest) (*Response, error)
	Move(context.Context, *MoveRequest) (*Response, error)
}

func RegisterRemoteStoreServer(s *grpc.Server, srv RemoteStoreServer) {
	s.RegisterService(&_RemoteStore_serviceDesc, srv)
}

func _RemoteStore_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteStoreServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RemoteStore/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteStoreServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteStore_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteStoreServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RemoteStore/Stat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteStoreServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteStore_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteStoreServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RemoteStore/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteStoreServer).Put(ctx, req.(*PutPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RemoteStore/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteStoreServer).Get(ctx, req.(*GetPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RemoteStore/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteStoreServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteStore_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteStoreServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RemoteStore/Move",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteStoreServer).Move(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RemoteStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RemoteStore",
	HandlerType: (*RemoteStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _RemoteStore_List_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _RemoteStore_Stat_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _RemoteStore_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RemoteStore_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RemoteStore_Delete_Handler,
		},
		{
			MethodName: "Move",
			Handler:    _RemoteStore_Move_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store.proto",
}
